### ISSUE TITLE
M8195A Configuration Issues

### ISSUE THREAD

**Issue by pbcarro** [kncrabtree/blackchirp#14]
Multiple small configuration changes need to be added at some point. 

-Chirp and marker amplitudes should be 1V, not the default 500mV.
-Trigging needs to be asynchronous, 1.5V
-Sample clock can be bumped to 65GHz

**Comment by kncrabtree** [comment]
These should all be easy.

Have you verified that asynchronous triggering maintains phase coherent averaging? With the Tektronix AWG system, the synchronous triggering was important to ensure that the chirp always starts on a clock cycle. You likely won't have any problems if you are not mixing with another oscillator, but if you introduce any upconversion/downconversion I think you may lose phase coherence with asynchronous triggering.

As an alternative, I can add it as an option you can edit in the config file.

**Comment by pbcarro** [comment]
Yes, I've been running it asynchronously. We're going to be able to direct synthesize/digitize up to 26GHz so that shouldn't be an issue. Phase stability in this scheme is extremely reliable. A config option is fine with me.

**Comment by kncrabtree** [comment]
I've addressed these with commit a69c38ca. Check it out and let me know if it works.
