### ISSUE TITLE
AWG Triggering

### ISSUE THREAD

**Issue by pbcarro** [kncrabtree/blackchirp#15]
The new configuration use the Quantum composer Ch D to trigger the AWG after the gas pulse. Ch D needs to be enabled for operation and the Ch D delay needs to control the gas-chirp delay.

**Comment by kncrabtree** [comment]
You can do this by setting PGEN_AWG=3 in the config.pri file. Run qmake and rebuild.

Soon, when I merge the "segmented" branch, you will be able to control this by assigning the AWG role to a channel on the pulse generator through the user interface.
