### ISSUE TITLE
Frames lost beyond first frame

### ISSUE THREAD

**Issue by laserkelvin** [kncrabtree/blackchirp#18]
As the title says, we're seeing the frame data beyond the first is lost upon aborting an experiment/closing blackchirp.

When the experiment is running, each frame has real FID data. When experiment is closed, the FIDs appear to basically go to noisy zero (but not exactly), and the FFT just returns something that resembles close to DC level.

I've looked in the .fid files in Python and see the same thing.

To my knowledge nothing has changed with the software, and since the frames have data during an experiment I don't think it's a hardware issue. We're sidestepping this issue in the meantime by just exporting each frame one by one before closing the experiment.

**Comment by kncrabtree** [comment]
That's definitely not ideal. I will add this to the list and get on it ASAP.

FYI, this is the last week of the quarter, and I'm swamped. So it might not be until next week or the week after unfortunately. Sorry!

**Comment by laserkelvin** [comment]
Definitely not a problem - the only victim of this is Brett so far. In the meantime we can just export the FIDs and do the processing offline :)

**Comment by kncrabtree** [comment]
This issue appears to have been fixed; perhaps with the merge of the segmented branch. If it reappears, feel free to open a new issue.
